### ISSUE TITLE
Threads don't have to be modelled

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-bts#68]
Might be better for general modelling performance to not have the threads modelled.
![Fusion360_2022-01-12_12-59-15](https://user-images.githubusercontent.com/32770145/149133112-a8674ee3-0342-4bcc-8427-8438fded47b3.png)

**Comment by mbz4** [comment]
fixed on camera gantry but not on motor mounts yet

**Comment by maidlam** [comment]
What I meant was that the threads in holes shouldn't be a 3D model, but when making a threaded hole, Fusion360 can show a texture instead.
There's an option in the "Hole" and "Thread" features to have the thread modeled. When there's no tick in the box, a texture will be shown instead.

The whole assembly should still show, which holes are threaded.

Picture is of the "Thread" feature in a motor mount side wall.
![2022-01-13_16-34-37](https://user-images.githubusercontent.com/32770145/149350637-41e0ba0c-c182-457e-aafc-411b7160d7f7.png)
